name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Deploy Goerli
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:goerli
      - name: Deploy Mumbai
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:mumbai
      - name: Deploy Mainnet
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:mainnet
      - name: Deploy Polygon
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:matic
      - name: Deploy Optimism
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:optimism
      - name: Deploy Arbitrum
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:arbitrum
      - name: Deploy Avalanche
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:avalanche
      - name: Deploy BSC
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:bsc
      - name: Deploy Fantom
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:fantom
      - name: Deploy Gnosis
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
        run: yarn deploy:gnosis
      - name: Build failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Build cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
